# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

python:
  - "2.7"

env:
  - TOXENV=py27

sudo: false

cache:
  apt: true
  directories:
    - $HOME/.cache/pip

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
      - python-lxml
      - python-cffi
      - openssl

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U pip
  - pip install -U tox jinja2 coveralls
  # To fix insecureplatformwarning of urllib3 for coveralls command
  - pip install -U pyopenssl ndg-httpsclient pyasn1

# command to run tests, e.g. python setup.py test
script:
  - tox -e $TOXENV
  - pip install . --user
  - python test_usage.py

after_success:
  - cp ${TRAVIS_BUILD_DIR}/.covera* ${TRAVIS_BUILD_DIR}/.tox/$TOXENV/
  - (cd ${TRAVIS_BUILD_DIR}/.tox/$TOXENV && coverage report -m && coveralls)

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: vauxoo
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: vauxoo/cfdilib
    condition: $TOXENV == py27
